'%dev':
   quarkus:
     datasource:
       db-kind: postgresql
       username: admin
       password: admin
       jdbc:
         url: jdbc:postgresql://localhost:5432/quarkus_dev
     hibernate-orm:
       database:
         generation: drop-and-create
       log:
         sql: true
     http:
       cors:
         ~: true
         origins: "http://localhost:3000"
         headers: "Content-Type,Authorization"
         methods: "GET,POST,PUT,DELETE"

quarkus:
   datasource:
     db-kind: postgresql
     username: admin
     password: admin
     jdbc:
       url: jdbc:postgresql://localhost:5432/quarkus_dev
   hibernate-orm:
     database:
       generation: update
     log:
       sql: false
   http:
     cors: false